version: "3.9"
services:
    app:
        container_name: 'go_docker_app'
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ./logs:/app/logs
            - .:/opt/app/api
        ports:
            - "5000:5000"
